on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
      - name: Deploy
        run: |
          ssh "${{ secrets.SSH_USER_HOST }}" "cd ~/chatty-monorepo; git pull; docker compose build frontend; docker compose build backend; docker compose up -d frontend"
